/**
 * @fileoverview MOCK SerpAPI helper for testing tool calling
 * 
 * This module provides mock responses for testing tool calling functionality.
 */

import { PackageInfo } from './packageAnalyzer';

// Re-export the interface
export interface DependencySecurityInfo {
  packageName: string;
  packageVersion?: string;
  vulnerabilities: {
    description: string;
    severity: 'critical' | 'high' | 'medium' | 'low' | 'unknown';
    affectedVersions?: string;
    fixedVersions?: string;
    url?: string;
  }[];
  recommendedVersion?: string;
  deprecationInfo?: string;
  packageHealth?: {
    lastUpdated?: string;
    status?: 'active' | 'maintained' | 'deprecated' | 'abandoned' | 'unknown';
    stars?: number;
    popularity?: string;
  };
  sources: string[];
}

// Mock data for known vulnerable packages
const MOCK_DATA: Record<string, DependencySecurityInfo> = {
  // NPM packages
  'axios': {
    packageName: 'axios',
    packageVersion: '0.21.1',
    vulnerabilities: [
      {
        description: 'Axios before 0.21.1 contains a Server-Side Request Forgery (SSRF) vulnerability where URLs with a protocol that resolves to localhost are not restricted by the url parser.',
        severity: 'high',
        affectedVersions: '<0.21.1',
        fixedVersions: '>=0.21.1',
        url: 'https://github.com/advisories/GHSA-xvch-5gv4-984h'
      }
    ],
    recommendedVersion: '1.3.4',
    packageHealth: {
      lastUpdated: 'March 2023',
      status: 'active',
      popularity: '94,000 stars'
    },
    sources: ['https://github.com/advisories/GHSA-xvch-5gv4-984h']
  },
  'log4js': {
    packageName: 'log4js',
    packageVersion: '5.0.0',
    vulnerabilities: [
      {
        description: 'Log4js before 6.4.0 is vulnerable to a ReDoS (Regular Expression Denial of Service) attack in the dateFormat function.',
        severity: 'medium',
        affectedVersions: '<6.4.0',
        fixedVersions: '>=6.4.0',
        url: 'https://github.com/log4js-node/log4js-node/security/advisories/GHSA-2qrg-x229-3v8q'
      }
    ],
    recommendedVersion: '6.7.1',
    packageHealth: {
      lastUpdated: 'November 2022',
      status: 'maintained',
      popularity: '5,600 stars'
    },
    sources: ['https://github.com/log4js-node/log4js-node/security/advisories/GHSA-2qrg-x229-3v8q']
  },
  'node-forge': {
    packageName: 'node-forge',
    packageVersion: '0.9.0',
    vulnerabilities: [
      {
        description: 'node-forge before 0.10.0 is vulnerable to Prototype Pollution via the util.setPath function.',
        severity: 'high',
        affectedVersions: '<0.10.0',
        fixedVersions: '>=0.10.0',
        url: 'https://github.com/advisories/GHSA-92xj-mqp7-vmcj'
      },
      {
        description: 'node-forge^0.7.0 <0.10.0 is vulnerable to an Improper Verification of Cryptographic Signature.',
        severity: 'critical',
        affectedVersions: '>=0.7.0 <0.10.0',
        fixedVersions: '>=0.10.0',
        url: 'https://github.com/advisories/GHSA-x4jg-mjrx-434g'
      }
    ],
    recommendedVersion: '1.3.1',
    packageHealth: {
      lastUpdated: 'February 2023',
      status: 'maintained',
      popularity: '3,800 stars'
    },
    sources: [
      'https://github.com/advisories/GHSA-92xj-mqp7-vmcj',
      'https://github.com/advisories/GHSA-x4jg-mjrx-434g'
    ]
  },

  // Python packages
  'django': {
    packageName: 'django',
    packageVersion: '2.2.13',
    vulnerabilities: [
      {
        description: 'Django 2.2 before 2.2.24, 3.1 before 3.1.12, and 3.2 before 3.2.4 has a potential directory traversal via django.contrib.admindocs.',
        severity: 'medium',
        affectedVersions: '>=2.2,<2.2.24',
        fixedVersions: '>=2.2.24',
        url: 'https://github.com/advisories/GHSA-8xwc-wf8f-4vxr'
      }
    ],
    recommendedVersion: '4.2.4',
    packageHealth: {
      lastUpdated: 'June 2023',
      status: 'active',
      popularity: 'Very popular'
    },
    sources: ['https://github.com/advisories/GHSA-8xwc-wf8f-4vxr']
  },
  'flask': {
    packageName: 'flask',
    packageVersion: '1.1.1',
    vulnerabilities: [
      {
        description: 'Flask 0.12.3 has a potential security issue with the way it handles requests.',
        severity: 'low',
        affectedVersions: '<2.0.0',
        fixedVersions: '>=2.0.0',
        url: 'https://github.com/pallets/flask/security/advisories'
      }
    ],
    recommendedVersion: '2.3.2',
    packageHealth: {
      lastUpdated: 'May 2023',
      status: 'active',
      popularity: 'Very popular'
    },
    sources: ['https://github.com/pallets/flask/security/advisories']
  },

  // PHP packages
  'symfony/http-foundation': {
    packageName: 'symfony/http-foundation',
    packageVersion: '4.4.0',
    vulnerabilities: [
      {
        description: 'In Symfony HttpFoundation before 4.4.7, 5.0.7, client-sent headers that are never generated by browsers were trusted and used for cache generation.',
        severity: 'medium',
        affectedVersions: '<4.4.7',
        fixedVersions: '>=4.4.7',
        url: 'https://github.com/advisories/GHSA-754h-5r27-7x3r'
      }
    ],
    recommendedVersion: '6.3.*',
    packageHealth: {
      lastUpdated: 'July 2023',
      status: 'active',
      popularity: 'Very popular'
    },
    sources: ['https://github.com/advisories/GHSA-754h-5r27-7x3r']
  }
};

/**
 * Check if SerpAPI is configured correctly - always returns true in mock
 * @returns True
 */
export function hasSerpApiConfig(): boolean {
  return true;
}

/**
 * Mock search for security information about a package
 * @param packageInfo The package information to search for
 * @param ecosystem The package ecosystem
 * @returns Mock security information about the package
 */
export async function searchPackageSecurity(
  packageInfo: PackageInfo,
  ecosystem: 'npm' | 'composer' | 'pip' | 'gem'
): Promise<DependencySecurityInfo | null> {
  // Add a small delay to simulate a network request
  await new Promise(resolve => setTimeout(resolve, 100));
  
  // Check if we have mock data for this package
  const mockData = MOCK_DATA[packageInfo.name];
  
  // If we don't have mock data, return a generic response
  if (!mockData) {
    return {
      packageName: packageInfo.name,
      packageVersion: packageInfo.version,
      vulnerabilities: [{
        description: 'No specific vulnerabilities found in mock data',
        severity: 'unknown'
      }],
      packageHealth: {
        status: 'maintained',
        lastUpdated: 'Recently'
      },
      sources: ['https://example.com/mock-source']
    };
  }
  
  return mockData;
}

/**
 * Search for multiple packages in batch
 * @param packages The packages to search for
 * @param ecosystem The package ecosystem
 * @param limit The maximum number of packages to search for
 * @returns Security information for the packages
 */
export async function batchSearchPackageSecurity(
  packages: PackageInfo[],
  ecosystem: 'npm' | 'composer' | 'pip' | 'gem',
  limit: number = 5
): Promise<DependencySecurityInfo[]> {
  const results: DependencySecurityInfo[] = [];
  
  // Limit the number of packages to search for
  const packagesToSearch = packages.slice(0, limit);
  
  // Search for each package
  for (const pkg of packagesToSearch) {
    const result = await searchPackageSecurity(pkg, ecosystem);
    if (result) {
      results.push(result);
    }
  }
  
  return results;
}