name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New review type
        - AI provider integration
        - CLI enhancement
        - Output format
        - Performance improvement
        - Developer workflow
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What pain point are you experiencing?
      placeholder: As a developer, I find it frustrating when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution. How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When reviewing large codebases...
        2. For teams that need to...
        3. In CI/CD pipelines where...
        
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature might work (CLI commands, configuration, etc.)
      render: shell
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - This is blocking my usage
        - Critical - This is preventing adoption
    validations:
      required: true
      
  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can provide feedback during development
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references related to this feature request