source "https://rubygems.org"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5.0"
gem "puma", "~> 6.0"
gem "jbuilder", "~> 2.11"
gem "bootsnap", ">= 1.4.4", require: false
gem "devise", "~> 4.9.0"
gem "pundit", "~> 2.3.0"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 6.0.0"
  gem "factory_bot_rails", "~> 6.2.0"
end

group :development do
  gem "web-console", ">= 4.2.0"
  gem "rack-mini-profiler", "~> 3.0"
  gem "listen", "~> 3.8"
  gem "rubocop", "~> 1.50", require: false
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver", ">= 4.10.0"
  gem "webdrivers", "~> 5.3.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]