#!/usr/bin/env node

/**
 * @fileoverview Script to generate src/version.ts from package.json
 *
 * This script reads the version from package.json and generates a TypeScript
 * file that exports the version constant. This ensures a single source of truth
 * for the version and eliminates potential mismatches between package.json and CLI.
 */

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Generate version.ts content
const versionTsContent = `/**
 * Auto-generated version file from package.json
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-version.js
 */

export const VERSION = '${version}';
`;

// Write to src/version.ts
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionTsPath, versionTsContent);

console.log(`📦 Generating version file from package.json...`);
console.log(`✅ Generated version.ts with version '${version}'`);
