name: Setup Repository Rules

on:
  workflow_dispatch:
    inputs:
      apply_branch_protection:
        description: 'Apply branch protection rules'
        required: true
        default: 'true'
        type: boolean
      setup_labels:
        description: 'Setup repository labels'
        required: true
        default: 'true'
        type: boolean

jobs:
  setup-repository:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      administration: write
      repository-projects: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Branch Protection
        if: ${{ inputs.apply_branch_protection == 'true' }}
        run: |
          # Apply main branch protection
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["Build", "Lint", "Test", "Type Check"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1,
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "restrict_dismissal_permissions": true
              },
              "restrictions": null,
              "required_conversation_resolution": true,
              "required_signatures": false,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'
      
      - name: Setup Repository Labels
        if: ${{ inputs.setup_labels == 'true' }}
        run: |
          # Define labels
          labels=(
            "bug,d73a4a,Something isn't working"
            "enhancement,a2eeef,New feature or request"
            "documentation,0075ca,Improvements or additions to documentation"
            "dependencies,0366d6,Pull requests that update a dependency file"
            "security,b60205,Security-related issues"
            "performance,f9ca24,Performance improvements"
            "needs-triage,ededed,Needs initial triage"
            "auto-merge,70db6a,Can be automatically merged"
            "wontfix,ffffff,This will not be worked on"
            "good first issue,7057ff,Good for newcomers"
            "help wanted,008672,Extra attention is needed"
            "provider:gemini,6f42c1,Related to Google Gemini provider"
            "provider:claude,9013fe,Related to Anthropic Claude provider"
            "provider:openai,159739,Related to OpenAI GPT provider"
            "provider:openrouter,0969da,Related to OpenRouter provider"
            "review-type:architectural,fbca04,Architectural review related"
            "review-type:security,d13212,Security review related"
            "review-type:performance,fef2c0,Performance review related"
            "review-type:quick-fixes,c5def5,Quick fixes review related"
          )
          
          # Create or update labels
          for label_info in "${labels[@]}"; do
            IFS=',' read -r name color description <<< "$label_info"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/labels \
              -d "{
                \"name\": \"$name\",
                \"color\": \"$color\",
                \"description\": \"$description\"
              }" || true
          done
      
      - name: Enable Vulnerability Alerts
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts
      
      - name: Configure Repository Settings
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{
              "has_issues": true,
              "has_projects": true,
              "has_wiki": false,
              "has_pages": false,
              "has_discussions": true,
              "allow_merge_commit": true,
              "allow_squash_merge": true,
              "allow_rebase_merge": false,
              "delete_branch_on_merge": true,
              "vulnerability_alerts": true
            }'