/**
 * Auto-generated version file from package.json
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-version.js
 */

export const VERSION = '4.4.7';
export const BUILD_NUMBER = 18;
export const VERSION_WITH_BUILD = '4.4.7 (build 18)';
