/**
 * Auto-generated version file from package.json
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-version.js
 */

export const VERSION = '4.6.1';
export const BUILD_NUMBER = 2;
export const VERSION_WITH_BUILD = '4.6.1 (build 2)';
