/**
 * Auto-generated version file from package.json
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-version.js
 */

export const VERSION = '4.4.4';
export const BUILD_NUMBER = 15;
export const VERSION_WITH_BUILD = '4.4.4 (build 15)';
